version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ai_ecommerce
      - PORT=5000
      - JWT_SECRET=supersecret
      - ADMIN_TOKEN=admin-secret-token
      - OPENAI_API_KEY=
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: sh -c "node seed/seed.js || true && node server.js"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

volumes:
  mongo-data:
